language: rust
rust:
- stable
cache: cargo
before_deploy:
- cargo build --release
deploy:
  provider: releases
  api_key:
    secure: Q4ayP9QOqB4u517M0qvvqRoZAEsv/3rwqvCLHPjJNa6UDSeOy9d+0G4+DTOetUq4qQW8FkQ2zePAYRJxtVThkZwKpacWEntkmf9euQWDeM/1+wGfr5I9bmVlI+bRK5zvFGVYfyFp9YxfNuLUvULNSHhn7pQ9WcorY8e1I2hqcXxB+cZUTP0U93gi9h2nFNX6olkVuYIbajeG/LyrDWxvWIBO7zN2sk1BfXwZWnGuSbpVmFg1GbCWgCK8NflJOGq00AawmNLjS5H5xi+H4Qf+2fl+ESd+9IofAI2cVA7VnoGppWF4nSBBDGybO4CCmP6PEw8JDT4uMmsl/zEXvL5Cn8ZuzLbGz5vUoHXWugbSeleiBh577EBZUToDfqD2e7JUldzktrdSZnw0B3LGYSmr9yT0L9fZUhmmQszSKICqlDNoItJHniC9FF9RSvcEsH5yGYkqRuRVkJJ33w5nPgYJwvKr+ewsE0vjJaiVCFse1h3YxT/VPHRXXCIMjEqSP4mVdMBkfEiht3D6ghLZzHgFoZ6OZQA74kjpx6Qy6bq6IOJ3Ctz+ug+AgFcL0PxoB/QDNeii1Klo7Q/9vzkvHEvOVDwIsjAVGvT8dFR+XEgYeCy8YrNeUCbCA4uXtbvVsb1Hff3jorS4Rr+cAc/Rd+gkHlJrC0EUm5wOqzDeGbIlnTE=
  file: target/release/ecs-run
  skip_cleanup: true
  on:
    repo: dalen/ecs-run
    tags: true
