language: rust
rust:
- stable
cache: cargo
before_deploy:
- cargo build --release
deploy:
  provider: releases
  api_token:
    secure: ieuXivbNnA1mjgzlYGRBM54fXKVK6HRnCDNWbNCh8qDJ1mpsd0gUWpRes0gKNbf4RKFhcEJwJ/Td6bs95qTRyXtouT62zWuwU8GN4U+1TrfRVZqyHHktfchNec85fVRShcuXkNX8qc+sV3Y47ZGNfgECw04LPUTPD66EtD5pCO7O2FX5b6zAAgZA1hAaQC0QtAr8bjVooj8YTzUUg+5mYKoKIpbcUKK8ST8aIhq6NNSy9dEqMhE6y75oZyEbaI+Y3Kw6OW8bDLAPNFIbdQ0z4zO5LDlsysS+uPUdZ7f1/YbQ0t992tu02d8k9I3PvfeC5GkEjQWifl+qclGwLZnTmRWEufRW8mVpSbGG2ri7AhHG1GdnHtSAz0P+BKUPjVAC7Wa8nkmfgBWrDFsH9L2UHfxRm7ww8gFquxgR1DmKk8bXQ6UBATg5Sc+BtmzqQw2/b+mY+KlU8Z7gJcrTp7QvxInHQA+dHQdbC51MtbQrPTjk07SPVbm3DDbuAi2Qm9/vnuagrNdwFPYwuwQMTpbJimGH1S6lHWj8g2EsAHC1SaceX6g1LTLivx6cJAjpFNChi1cIP1BAZiaJPs9s7BQb2a1Ydd6vKF3qc1AUCDdTCo/iBmtQaBa91+shbc+eO7BRZkEqxLvk5T2BO07aaQUqdi48cMHRUPins7i3JARTStQ=
  skip_cleanup: true
  file: 'target/release/ecs-run'
  on:
    tags: true
